---
initial_conditions:
  type: "ccake" # Possible values are: ["ccake", "iccing", "hdf5"]
  file: "/u/kpala/git_repos/viscous-gubser-with-conserved-charges/data/output/analytic_solutions/EoS2/mu_over_T_0.3/VGCC_initial_condition.dat" # Path to the initial conditions file
  t0: 1.000000 # tau0 = \sqrt(t^2-z^2) in fm/c. Must match the value for initial condition file.
  dimension: 2 # (1+1)D, (2+1)D or (3+1)D simulation
  input_as_entropy: false # if false, input will be interpreted as energy density
parameters:
  dt: 0.001 # time-step of the simulation in fm/c
  h_T:  0.100000  # Smoothing parameter inside kernel, in the transverse direction (in fm)
  h_eta:  0.100000  # Smoothing parameter inside kernel in the longitudinal direction
  rk_order: 2
  kernel_type: "cubic_spline" # Kernel type. Possible values are: ["cubic_spline"]
  energy_cutoff: 0.0 # GeV/fm^3 - Particles with less than this energy will be deleted before starting the evolution
  buffer_particles:
    enabled: true # Set to true to include buffer particles. May help stability.
    circular: true # whether to buffer with entire grid or just circular padding.
    padding_thickness: .1 # if circular buffer is true, specifies the fractional amount
                          # of padding to add beyond the point with maximum distance from origin
eos:
  online_inverter_enabled: true
  preinverted_eos_path: /u/kpala/git_repos/test/test_chain/tables
  type: "conformal" # Possible values are: ["table", "tanh_conformal", "conformal", "conformal_diagonal"]
  path: "EoS/Houston" # If type is "table", the path to the equation of state table.
particlization:
  enabled: true # set to true to output particlization hypersurface
  type: "fixed_T" # Possible values are: ["fixed_T"]
  T: 153.334025 # Temperature of the particlization hypersurface (in MeV) # T = 153.334025 MeV corresponds to eps = 1.0 GeV/fm^3 for the conformal EoS
hydro:
  baryon_charge_enabled: true
  electric_charge_enabled: true
  strange_charge_enabled: true
  viscous_parameters:
    diffusion:
      input_initial_diffusion: false
      mode:  constant_over_T2
      constant_kappa_over_T2:
      - [0., -0., 0.0]
      - [-0., 0., 0.]
      - [0.0, 0., 0.0]
      relaxation_mode: constant_over_T
    bulk:
      bulk_from_trace: false
      constant_zeta_over_s: 0.00
      cs2_dependent_zeta_A: 1.67552
      cs2_dependent_zeta_p: 2.0
      mode: constant
      modulate_with_tanh: false
      relaxation_mode: default
      delta_PiPi_mode: israel-stewart
      lambda_Pipi_mode: default
      phi1_mode: disabled
      phi3_mode: disabled
    shear:
      input_initial_shear: true
      constant_eta_over_s: 0.2
      mode: constant
      relaxation_mode: gubser
      use_vorticity: false
      delta_pipi_mode: default
      tau_pipi_mode: disabled
      lambda_piPi_mode: disabled
      phi6_mode: disabled
      phi7_mode: disabled
output:
  calculate_observables: false
  hdf_evolution: false
  print_conservation_state: true
  txt_evolution: true
  check_causality: true

