eos:
  online_inverter_enabled: true
  path: /u/kpala/git_repos/test/test_chain/tables
  preinverted_eos_path: default
  type: table
hydro:
  baryon_charge_enabled: true
  electric_charge_enabled: true
  strange_charge_enabled: true
  viscous_parameters:
    diffusion:
      input_initial_diffusion: false
      mode:  constant_over_T2
      constant_kappa_over_T2:
      - [0., -0., 0.0]
      - [-0., 0., 0.]
      - [0.0, 0., 0.0]
      relaxation_mode: constant_over_T
    bulk:
      bulk_from_trace: false
      constant_zeta_over_s: 0.00
      cs2_dependent_zeta_A: 1.67552
      cs2_dependent_zeta_p: 2.0
      mode: constant
      modulate_with_tanh: false
      relaxation_mode: default
      delta_PiPi_mode: disabled
      lambda_Pipi_mode: disabled
      phi1_mode: disabled
      phi3_mode: disabled
    shear:
      input_initial_shear: false
      constant_eta_over_s: 0.12
      mode: constant
      relaxation_mode: default
      delta_pipi_mode: default
      use_vorticity: true
      tau_pipi_mode: default
      lambda_piPi_mode: default
      phi6_mode: default
      phi7_mode: default
initial_conditions:
  coordinate_system: hyperbolic
  dimension: 2
  file: /u/kpala/densities100.dat
  input_as_entropy: false
  t0: 0.6
  type: ICCING
output:
  calculate_observables: false
  hdf_evolution: false
  print_conservation_state: true
  txt_evolution: true
  check_causality: true
parameters:
  buffer_particles:
    circular: false
    enabled: false
    padding_thickness: 0.1
  dt: 0.05
  energy_cutoff: 0.15
  h_T: 0.3
  h_eta: 0.3
  kernel_type: cubic_spline
  max_tau: 30.0
  rk_order: 2
particlization:
  T: 150
  enabled: true
  type: fixed_T
