---
Initial_conditions:
  type: "ccake" # Possible values are: ["ccake", "iccing", "hdf5"]
  file: "/CCAKE/my_tests/long_data/ic_long_tau_1.0.dat" # Path to the initial conditions file
  t0: 1.0 # tau0 = \sqrt(t^2-z^2) in fm/c. Must match the value for initial condition file.
  dimension: 1 # (1+1)D, (2+1)D or (3+1)D simulation
  input_as_entropy: false # if false, input will be interpreted as energy density
parameters:
  dt: 0.05 # time-step of the simulation in fm/c
  h_T:  0.500000  # Smothing parameter inside kernel, in the transverse direction (in fm)
  h_eta:  0.500000  # Smothing parameter inside kernel in the longitudinal direction
  kernel_type: "cubic_spline" # Kernel type. Possible values are: ["cubic_spline"]
  energy_cutoff: 0.15 # GeV/fm^3 - Particles with less than this energy will be deleted before starting the evolution
  buffer_particles:
    enabled: true # Set to true to include buffer particles. May help stability.
    circular: true # whether to buffer with entire grid or just circular padding.
    padding_thickness: .1 # if circular buffer is true, specifies the fractional amount
eos:
  type: "conformal" # Possible values are: ["table", "conformal"]
  path: "EoS/Houston" # If type is "table", the path to the equation of state table.
particlization:
  enabled: false # Set to true to output particlization hypersurface
  type: "fixed_T" # Possible values are: ["fixed_T"]
  T: 150.00000 # Temperature of the particlization hypersurface (in MeV)
hydro:
  baryon_charge_enabled: false # Set to false to disable baryon charge evolution
  strange_charge_enabled: false # Set to false to disable strange charge evolution
  electric_charge_enabled: false # Set to false to disable electric charge evolution
  viscous_parameters:
    shear:
      mode: "constant" # Possible values are: ["constant", "disabled"]
      constant_eta_over_s: 0.0 # Value of the constant shear viscosity
      relaxation_mode: "default" # How shear relaxation coeffiecient is computed. Possible values are: ["default"]
    bulk:
      mode: "constant"
      constant_zeta_over_s: 0.0
      cs2_dependent_zeta_A: 0.0
      cs2_dependent_zeta_p: 0.0
      relaxation_mode: "default"
      modulate_with_tanh: false #If true, will modulate the bulk viscosity
                               #with a tanh function below transition temperature
output:
  print_conservation_state: true
  hdf_evolution: false
  txt_evolution: true
